#!/bin/bash
# Wait for specific checkpoints and gate on a REAL BEAM. Launch detached:
#     nohup bash cube555/scripts/21_gate_chain.sh > cube555/logs/gate_chain.log 2>&1 &
#
# Waits on FILE EXISTENCE, never on a process pattern: `pgrep -f`/`pkill -f` match the
# checking command's own arguments and a waiter written that way loops forever.
#
# Two gates, both cheap, both answering something a training curve cannot:
#   LADDER  beam length vs scramble length over pids 34+L. Where the curve flattens is
#           where true distance saturates, which is the direct measurement of the
#           diameter that k_max = 80 currently rests on a counting bound for. If it
#           flattens far below 80 the run is mis-parameterised and should be restarted;
#           that is worth knowing at hour 10, not hour 38.
#   SMOKE   12 fully-mixed pids at 2^20. Catastrophe detection ONLY. Expect a long flat
#           plateau while every offline probe keeps improving -- on 444 the beam sat in a
#           243-249 band from ep3999 to ep10673 while deep top-1 rose monotonically.
#           Do NOT kill on a plateau.
#
# Do not edit this file while bash is executing it: the interpreter re-reads from a byte
# offset and will run garbage. Kill, edit, relaunch.
set -u
cd /home/artgor/cayley
PY=.venv/bin/python
LADDER=40,44,50,54,59,64,69,74,79,84,94,104,114,134,184,334,1034

gate () {          # $1 = arm dir, $2 = epoch tag
  local ck="cube555/models/$1/epoch_$2.pt"
  while [ ! -f "$ck" ]; do sleep 120; done
  sleep 30         # let the torch.save finish
  echo "=========== GATE $1 $2  $(date -u +%H:%M:%S) ==========="
  $PY cube555/scripts/30_solve.py --checkpoint "$ck" --pids "$LADDER" \
      --beams 262144 --max-steps 160 --bf16 --internal-batch-size 262144 \
      --out "cube555/bench/ladder_$1_$2.csv" 2>&1 | tail -20
  $PY cube555/scripts/30_solve.py --checkpoint "$ck" --pids smoke \
      --beams 1048576 --max-steps 160 --bf16 --internal-batch-size 262144 \
      --out "cube555/bench/smoke_$1_$2.csv" 2>&1 | tail -16
  echo "=========== END GATE $1 $2 ==========="
}

gate q555_a 002399
gate q555_a 005999
echo "ALL GATES DONE $(date -u +%H:%M:%S)"
