"""Exact structured coordinates for Christopher's Jewel.

The 48-sticker puzzle has six fixed C4 ring pieces and twelve permuted,
oriented edges.  Reachable states satisfy two parity constraints, so a state
fits in 51 bits: 12! * 2**22 states.

Move data is the piece-coordinate form generated by PuzzleGeometry in
third_party/twips/third_party/twsearch_legacy/samples/main/Christophers_jewel.tws.
Competition names are matched to those moves by their face-letter multisets.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import factorial
from typing import Iterable, Sequence

import numpy as np


BASE_ACTION_NAMES = (
    "DBRRF",
    "UBBBLL",
    "DFLBL",
    "URBRBB",
    "DBLBBBR",
    "ULFR",
)
ACTION_NAMES = tuple(name for base in BASE_ACTION_NAMES for name in (base, f"-{base}"))
ACTION_TO_INDEX = {name: i for i, name in enumerate(ACTION_NAMES)}
INVERSE_ACTION = np.asarray([i ^ 1 for i in range(12)], dtype=np.int8)

# new_edge[slot] = old_edge[src[slot]], with the listed XOR orientation delta.
_BASE_EDGE_SRC = np.asarray(
    [
        [0, 1, 8, 2, 4, 3, 6, 7, 5, 9, 10, 11],  # FRND -> DBRRF
        [0, 1, 2, 3, 4, 5, 9, 7, 8, 10, 11, 6],  # BULM -> UBBBLL
        [11, 1, 0, 3, 4, 5, 6, 2, 8, 9, 10, 7],  # FDML -> DFLBL
        [0, 5, 2, 3, 9, 4, 6, 7, 8, 1, 10, 11],  # BNRU -> URBRBB
        [0, 1, 2, 3, 8, 5, 6, 10, 7, 9, 4, 11],  # BMDN -> DBLBBBR
        [3, 6, 2, 1, 4, 5, 0, 7, 8, 9, 10, 11],  # FLUR -> ULFR
    ],
    dtype=np.uint8,
)
_BASE_EDGE_FLIP = np.asarray(
    [
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
        [1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    ],
    dtype=np.uint8,
)
_BASE_RING_INDEX = np.asarray([2, 4, 5, 1, 3, 0], dtype=np.uint8)


def _compose_moves(
    src1: np.ndarray,
    flip1: np.ndarray,
    ring1: np.ndarray,
    src2: np.ndarray,
    flip2: np.ndarray,
    ring2: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compose transforms in application order: first move 1, then move 2."""
    return (
        src1[src2],
        np.bitwise_xor(flip1[src2], flip2),
        (ring1 + ring2) & 3,
    )


def _make_actions() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    srcs: list[np.ndarray] = []
    flips: list[np.ndarray] = []
    rings: list[np.ndarray] = []
    identity_src = np.arange(12, dtype=np.uint8)
    zero_flip = np.zeros(12, dtype=np.uint8)
    for base_i in range(6):
        base_ring = np.zeros(6, dtype=np.uint8)
        base_ring[_BASE_RING_INDEX[base_i]] = 1
        src = _BASE_EDGE_SRC[base_i]
        # In the Ksolve/TWS format the orientation row is indexed by the
        # moved source positions.  Convert it to the target-indexed delta used
        # by ``apply_action`` (new[target] = old[src[target]] xor delta[target]).
        flip = _BASE_EDGE_FLIP[base_i][src]
        inv_src, inv_flip, inv_ring = identity_src, zero_flip, np.zeros(6, dtype=np.uint8)
        for _ in range(3):
            inv_src, inv_flip, inv_ring = _compose_moves(
                inv_src, inv_flip, inv_ring, src, flip, base_ring
            )
        srcs.extend((src.copy(), inv_src.copy()))
        flips.extend((flip.copy(), inv_flip.copy()))
        rings.extend((base_ring.copy(), inv_ring.copy()))
    return np.stack(srcs), np.stack(flips), np.stack(rings)


ACTION_EDGE_SRC, ACTION_EDGE_FLIP, ACTION_RING_DELTA = _make_actions()

FACTORIAL = np.asarray([factorial(i) for i in range(13)], dtype=np.uint64)
GROUP_ORDER = factorial(12) * (1 << 22)


def permutation_parity(perm: Sequence[int] | np.ndarray) -> int:
    p = np.asarray(perm)
    inversions = 0
    for i in range(11):
        inversions += int(np.count_nonzero(p[i + 1 :] < p[i]))
    return inversions & 1


def rank_permutation(perm: Sequence[int] | np.ndarray) -> int:
    p = np.asarray(perm, dtype=np.uint8)
    rank = 0
    for i in range(11):
        rank += int(np.count_nonzero(p[i + 1 :] < p[i])) * factorial(11 - i)
    return rank


def unrank_permutation(rank: int) -> np.ndarray:
    if not 0 <= rank < factorial(12):
        raise ValueError(f"permutation rank out of range: {rank}")
    available = list(range(12))
    out = np.empty(12, dtype=np.uint8)
    remainder = int(rank)
    for i in range(12):
        weight = factorial(11 - i)
        digit, remainder = divmod(remainder, weight)
        out[i] = available.pop(digit)
    return out


@dataclass(frozen=True, slots=True)
class JewelState:
    edge_perm: np.ndarray
    edge_ori: np.ndarray
    ring_ori: np.ndarray

    def __post_init__(self) -> None:
        object.__setattr__(self, "edge_perm", np.asarray(self.edge_perm, dtype=np.uint8))
        object.__setattr__(self, "edge_ori", np.asarray(self.edge_ori, dtype=np.uint8))
        object.__setattr__(self, "ring_ori", np.asarray(self.ring_ori, dtype=np.uint8))

    def validate(self) -> None:
        if self.edge_perm.shape != (12,) or set(map(int, self.edge_perm)) != set(range(12)):
            raise ValueError("edge_perm must be a permutation of 0..11")
        if self.edge_ori.shape != (12,) or np.any(self.edge_ori > 1):
            raise ValueError("edge_ori must contain 12 bits")
        if self.ring_ori.shape != (6,) or np.any(self.ring_ori > 3):
            raise ValueError("ring_ori must contain six values in 0..3")
        if int(self.edge_ori.sum()) & 1:
            raise ValueError("edge orientation parity must be even")
        if (int(self.ring_ori.sum()) & 1) != permutation_parity(self.edge_perm):
            raise ValueError("ring-twist parity must equal edge-permutation parity")

    def rank(self) -> int:
        self.validate()
        edge_bits = 0
        for i in range(11):
            edge_bits |= int(self.edge_ori[i]) << i
        ring_bits = 0
        for i in range(5):
            ring_bits |= int(self.ring_ori[i]) << (2 * i)
        ring_bits |= (int(self.ring_ori[5]) >> 1) << 10
        return ((rank_permutation(self.edge_perm) << 11) | edge_bits) << 11 | ring_bits

    @classmethod
    def unrank(cls, value: int) -> "JewelState":
        if not 0 <= value < GROUP_ORDER:
            raise ValueError(f"state rank out of range: {value}")
        ring_bits = value & ((1 << 11) - 1)
        value >>= 11
        edge_bits = value & ((1 << 11) - 1)
        perm_rank = value >> 11
        perm = unrank_permutation(perm_rank)

        edge_ori = np.empty(12, dtype=np.uint8)
        for i in range(11):
            edge_ori[i] = (edge_bits >> i) & 1
        edge_ori[11] = int(edge_ori[:11].sum()) & 1

        ring_ori = np.empty(6, dtype=np.uint8)
        for i in range(5):
            ring_ori[i] = (ring_bits >> (2 * i)) & 3
        ring5_high = (ring_bits >> 10) & 1
        ring5_low = permutation_parity(perm) ^ (int(ring_ori[:5].sum()) & 1)
        ring_ori[5] = (ring5_high << 1) | ring5_low
        state = cls(perm, edge_ori, ring_ori)
        state.validate()
        return state


SOLVED = JewelState(
    np.arange(12, dtype=np.uint8),
    np.zeros(12, dtype=np.uint8),
    np.zeros(6, dtype=np.uint8),
)


def apply_action(state: JewelState, action: int | str) -> JewelState:
    action_i = ACTION_TO_INDEX[action] if isinstance(action, str) else int(action)
    if not 0 <= action_i < 12:
        raise ValueError(f"invalid action: {action}")
    src = ACTION_EDGE_SRC[action_i]
    return JewelState(
        state.edge_perm[src],
        np.bitwise_xor(state.edge_ori[src], ACTION_EDGE_FLIP[action_i]),
        (state.ring_ori + ACTION_RING_DELTA[action_i]) & 3,
    )


def apply_path(state: JewelState, actions: Iterable[int | str]) -> JewelState:
    out = state
    for action in actions:
        out = apply_action(out, action)
    return out


def inverse_path(actions: Sequence[int]) -> list[int]:
    return [int(INVERSE_ACTION[a]) for a in reversed(actions)]


def parse_path(path: str) -> list[int]:
    if not path:
        return []
    return [ACTION_TO_INDEX[token] for token in path.split(".")]


def format_path(actions: Sequence[int]) -> str:
    return ".".join(ACTION_NAMES[int(a)] for a in actions)


def apply_action_batch(
    edge_perm: np.ndarray,
    edge_ori: np.ndarray,
    ring_ori: np.ndarray,
    action: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    src = ACTION_EDGE_SRC[action]
    return (
        edge_perm[:, src],
        np.bitwise_xor(edge_ori[:, src], ACTION_EDGE_FLIP[action]),
        (ring_ori + ACTION_RING_DELTA[action]) & 3,
    )


def rank_states(
    edge_perm: np.ndarray,
    edge_ori: np.ndarray,
    ring_ori: np.ndarray,
) -> np.ndarray:
    """Vectorized 51-bit rank for valid structured states."""
    edge_perm = np.asarray(edge_perm, dtype=np.uint8)
    n = edge_perm.shape[0]
    perm_rank = np.zeros(n, dtype=np.uint64)
    for i in range(11):
        count = np.sum(edge_perm[:, i + 1 :] < edge_perm[:, i : i + 1], axis=1, dtype=np.uint64)
        perm_rank += count * FACTORIAL[11 - i]
    edge_bits = np.zeros(n, dtype=np.uint64)
    for i in range(11):
        edge_bits |= edge_ori[:, i].astype(np.uint64) << np.uint64(i)
    ring_bits = np.zeros(n, dtype=np.uint64)
    for i in range(5):
        ring_bits |= ring_ori[:, i].astype(np.uint64) << np.uint64(2 * i)
    ring_bits |= (ring_ori[:, 5].astype(np.uint64) >> np.uint64(1)) << np.uint64(10)
    return ((perm_rank << np.uint64(11)) | edge_bits) << np.uint64(11) | ring_bits
