"""Exact structural decomposition for a classical 6x6x6 solver.

The 216 exact stickers split into nine 24-position group orbits.  One orbit is
the corner stickers.  Four are centre-piece orbits.  The remaining four are two
pairs of equivariantly moving wing-sticker orbits; each pair represents one
24-piece physical wing cluster.

This module discovers that structure from the move permutations.  It does not
hard-code sticker indices, so it remains valid if a competition instance uses a
different sticker ordering.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence


Permutation = tuple[int, ...]
Orbit = tuple[int, ...]
ParityVector = tuple[int, ...]


@dataclass(frozen=True)
class WingPair:
    """Two sticker orbits belonging to the same physical wing pieces."""

    left: Orbit
    right: Orbit
    # Entry i is the right-orbit position corresponding to left[i].
    right_position_by_left_index: tuple[int, ...]

    def as_global_map(self) -> dict[int, int]:
        return dict(zip(self.left, self.right_position_by_left_index, strict=True))


@dataclass(frozen=True)
class Cube666Decomposition:
    """Discovered physical clusters and their move-level parity effects."""

    size: int
    corner_orbit: Orbit
    center_orbits: tuple[Orbit, ...]
    wing_pairs: tuple[WingPair, ...]
    inner_move_names: tuple[str, ...]
    parity_effects: tuple[tuple[str, ParityVector], ...]

    @property
    def physical_clusters(self) -> tuple[Orbit, ...]:
        """The six 24-piece clusters controlled by inner-slice parity."""

        wing_clusters = tuple(pair.left for pair in self.wing_pairs)
        return self.center_orbits + wing_clusters

    @property
    def cluster_names(self) -> tuple[str, ...]:
        centers = tuple(f"center_{index}" for index in range(len(self.center_orbits)))
        wings = tuple(f"wing_{index}" for index in range(len(self.wing_pairs)))
        return centers + wings

    def parity_effect_dict(self) -> dict[str, ParityVector]:
        return dict(self.parity_effects)


@dataclass(frozen=True)
class ClusterResidual:
    name: str
    parity: int
    cycles: tuple[tuple[int, ...], ...]
    unrestricted_three_cycles: int | None


@dataclass(frozen=True)
class ResidualReport:
    corner_parity: int
    clusters: tuple[ClusterResidual, ...]

    @property
    def parity_vector(self) -> ParityVector:
        return tuple(cluster.parity for cluster in self.clusters)

    @property
    def all_even(self) -> bool:
        return not any(self.parity_vector)

    @property
    def unrestricted_three_cycles(self) -> int | None:
        if not self.all_even:
            return None
        return sum(cluster.unrestricted_three_cycles or 0 for cluster in self.clusters)


def _validate_generators(generators: Mapping[str, Sequence[int]]) -> tuple[int, dict[str, Permutation]]:
    if not generators:
        raise ValueError("at least one generator is required")
    normalized = {name: tuple(int(value) for value in permutation) for name, permutation in generators.items()}
    sizes = {len(permutation) for permutation in normalized.values()}
    if len(sizes) != 1:
        raise ValueError(f"generator lengths disagree: {sorted(sizes)}")
    n = sizes.pop()
    expected = set(range(n))
    for name, permutation in normalized.items():
        if set(permutation) != expected:
            raise ValueError(f"generator {name!r} is not a permutation of 0..{n - 1}")
    return n, normalized


def position_orbits(generators: Mapping[str, Sequence[int]]) -> tuple[Orbit, ...]:
    """Return position orbits of the group generated by ``generators``."""

    n, normalized = _validate_generators(generators)
    permutations = tuple(normalized.values())
    unseen = set(range(n))
    orbits: list[Orbit] = []
    while unseen:
        root = min(unseen)
        reached = {root}
        queue = deque((root,))
        while queue:
            position = queue.popleft()
            for permutation in permutations:
                image = permutation[position]
                if image not in reached:
                    reached.add(image)
                    queue.append(image)
        unseen.difference_update(reached)
        orbits.append(tuple(sorted(reached)))
    return tuple(sorted(orbits, key=lambda orbit: (len(orbit), orbit[0])))


def _move_support_signature(orbit: Orbit, generators: Mapping[str, Permutation]) -> tuple[str, ...]:
    return tuple(
        name
        for name, permutation in generators.items()
        if any(permutation[position] != position for position in orbit)
    )


def _equivariant_bijections(
    left: Orbit,
    right: Orbit,
    generators: Mapping[str, Permutation],
) -> tuple[tuple[int, ...], ...]:
    """Find all generator-commuting bijections from ``left`` to ``right``."""

    if len(left) != len(right):
        return ()
    left_set = set(left)
    right_set = set(right)
    permutations = tuple(generators.values())
    anchor = left[0]
    answers: list[tuple[int, ...]] = []

    for anchor_image in right:
        image_by_position = {anchor: anchor_image}
        used_images = {anchor_image}
        queue = deque((anchor,))
        valid = True
        while queue and valid:
            position = queue.popleft()
            image = image_by_position[position]
            for permutation in permutations:
                next_position = permutation[position]
                next_image = permutation[image]
                if next_position not in left_set or next_image not in right_set:
                    valid = False
                    break
                old_image = image_by_position.get(next_position)
                if old_image is not None:
                    if old_image != next_image:
                        valid = False
                        break
                    continue
                if next_image in used_images:
                    valid = False
                    break
                image_by_position[next_position] = next_image
                used_images.add(next_image)
                queue.append(next_position)

        if valid and len(image_by_position) == len(left) and len(used_images) == len(right):
            candidate = tuple(image_by_position[position] for position in left)
            if candidate not in answers:
                answers.append(candidate)
    return tuple(sorted(answers))


def _local_restriction(permutation: Sequence[int], orbit: Orbit) -> Permutation:
    local_index = {position: index for index, position in enumerate(orbit)}
    try:
        return tuple(local_index[permutation[position]] for position in orbit)
    except KeyError as exc:
        raise ValueError("generator does not preserve a discovered orbit") from exc


def permutation_parity(permutation: Sequence[int]) -> int:
    """Return 0 for an even permutation and 1 for an odd permutation."""

    n = len(permutation)
    if set(permutation) != set(range(n)):
        raise ValueError("input is not a permutation of 0..N-1")
    seen = [False] * n
    parity = 0
    for start in range(n):
        if seen[start]:
            continue
        length = 0
        position = start
        while not seen[position]:
            seen[position] = True
            length += 1
            position = permutation[position]
        parity ^= (length - 1) & 1
    return parity


def build_decomposition(generators: Mapping[str, Sequence[int]]) -> Cube666Decomposition:
    """Discover corners, four centre clusters, and two physical wing clusters."""

    n, normalized = _validate_generators(generators)
    orbits = position_orbits(normalized)
    if n != 216 or len(orbits) != 9 or {len(orbit) for orbit in orbits} != {24}:
        raise ValueError(
            "expected an exact 6x6x6 representation with nine 24-position orbits; "
            f"got size={n}, orbit_sizes={[len(orbit) for orbit in orbits]}"
        )

    active_counts = {
        orbit: len(_move_support_signature(orbit, normalized))
        for orbit in orbits
    }
    minimum_active = min(active_counts.values())
    corner_candidates = [orbit for orbit, count in active_counts.items() if count == minimum_active]
    if len(corner_candidates) != 1:
        raise ValueError(
            "could not uniquely identify the corner orbit by move support; "
            f"minimum-active candidates={len(corner_candidates)}"
        )
    corner = corner_candidates[0]
    noncorner = tuple(orbit for orbit in orbits if orbit != corner)

    pair_edges: list[tuple[int, int, tuple[int, ...]]] = []
    for left_index, left in enumerate(noncorner):
        for right_index in range(left_index + 1, len(noncorner)):
            right = noncorner[right_index]
            bijections = _equivariant_bijections(left, right, normalized)
            if bijections:
                pair_edges.append((left_index, right_index, bijections[0]))

    if len(pair_edges) != 2 or len({index for edge in pair_edges for index in edge[:2]}) != 4:
        diagnostic_edges = [(left, right) for left, right, _ in pair_edges]
        raise ValueError(
            "expected exactly two disjoint equivariant wing-orbit pairs; "
            f"found edges={diagnostic_edges}"
        )

    paired_indices = {index for edge in pair_edges for index in edge[:2]}
    centers = tuple(noncorner[index] for index in range(len(noncorner)) if index not in paired_indices)
    wing_pairs = tuple(
        WingPair(noncorner[left], noncorner[right], image)
        for left, right, image in pair_edges
    )
    if len(centers) != 4 or len(wing_pairs) != 2:
        raise AssertionError("internal cluster classification error")

    inner_moves = tuple(
        name
        for name, permutation in normalized.items()
        if all(permutation[position] == position for position in corner)
    )
    clusters = centers + tuple(pair.left for pair in wing_pairs)
    effects: list[tuple[str, ParityVector]] = []
    for name in inner_moves:
        permutation = normalized[name]
        vector = tuple(permutation_parity(_local_restriction(permutation, orbit)) for orbit in clusters)
        for pair, wing_parity in zip(wing_pairs, vector[len(centers) :], strict=True):
            paired_parity = permutation_parity(_local_restriction(permutation, pair.right))
            if paired_parity != wing_parity:
                raise ValueError(f"wing sticker parities disagree for move {name!r}")
        effects.append((name, vector))

    return Cube666Decomposition(
        size=n,
        corner_orbit=corner,
        center_orbits=centers,
        wing_pairs=wing_pairs,
        inner_move_names=inner_moves,
        parity_effects=tuple(effects),
    )


def cluster_permutation(
    state: Sequence[int],
    target: Sequence[int],
    orbit: Orbit,
) -> Permutation:
    """Express the current stickers in an orbit as target-slot source indices."""

    if len(state) != len(target):
        raise ValueError("state and target lengths differ")
    if len(set(target)) != len(target):
        raise ValueError("target stickers must be unique")
    target_position = {sticker: position for position, sticker in enumerate(target)}
    local_index = {position: index for index, position in enumerate(orbit)}
    result: list[int] = []
    for position in orbit:
        sticker = state[position]
        if sticker not in target_position:
            raise ValueError(f"state contains sticker {sticker!r} absent from target")
        source_position = target_position[sticker]
        if source_position not in local_index:
            raise ValueError("state moves a sticker between invariant position orbits")
        result.append(local_index[source_position])
    if set(result) != set(range(len(orbit))):
        raise ValueError("cluster does not contain each target sticker exactly once")
    return tuple(result)


def permutation_cycles(permutation: Sequence[int]) -> tuple[tuple[int, ...], ...]:
    """Return nontrivial cycles in deterministic order."""

    n = len(permutation)
    if set(permutation) != set(range(n)):
        raise ValueError("input is not a permutation of 0..N-1")
    seen = [False] * n
    cycles: list[tuple[int, ...]] = []
    for start in range(n):
        if seen[start]:
            continue
        cycle: list[int] = []
        position = start
        while not seen[position]:
            seen[position] = True
            cycle.append(position)
            position = permutation[position]
        if len(cycle) > 1:
            cycles.append(tuple(cycle))
    return tuple(cycles)


def minimum_unrestricted_three_cycles(permutation: Sequence[int]) -> int:
    """Exact 3-cycle word length for an even permutation.

    This assumes any 3-cycle on the cluster is available at unit cost.  It is an
    exact algebraic residual count, not a face-turn metric estimate.
    """

    if permutation_parity(permutation):
        raise ValueError("an odd permutation cannot be expressed using only 3-cycles")
    return sum(len(cycle) // 2 for cycle in permutation_cycles(permutation))


def _verify_wing_synchronization(
    state: Sequence[int],
    target: Sequence[int],
    pair: WingPair,
) -> None:
    left_permutation = cluster_permutation(state, target, pair.left)
    right_permutation = cluster_permutation(state, target, pair.right)
    left_index = {position: index for index, position in enumerate(pair.left)}
    right_index = {position: index for index, position in enumerate(pair.right)}
    phi_local = tuple(right_index[position] for position in pair.right_position_by_left_index)
    for left_destination, left_source in enumerate(left_permutation):
        right_destination = phi_local[left_destination]
        expected_right_source = phi_local[left_source]
        if right_permutation[right_destination] != expected_right_source:
            raise ValueError("paired wing sticker orbits do not encode synchronized physical pieces")


def residual_report(
    state: Sequence[int],
    target: Sequence[int],
    decomposition: Cube666Decomposition,
) -> ResidualReport:
    """Return cluster parities, cycles, and exact unrestricted 3-cycle counts."""

    if len(state) != decomposition.size or len(target) != decomposition.size:
        raise ValueError(f"expected state and target length {decomposition.size}")
    for pair in decomposition.wing_pairs:
        _verify_wing_synchronization(state, target, pair)

    corner_permutation = cluster_permutation(state, target, decomposition.corner_orbit)
    corner_parity = permutation_parity(corner_permutation)
    reports: list[ClusterResidual] = []
    for name, orbit in zip(
        decomposition.cluster_names,
        decomposition.physical_clusters,
        strict=True,
    ):
        permutation = cluster_permutation(state, target, orbit)
        parity = permutation_parity(permutation)
        reports.append(
            ClusterResidual(
                name=name,
                parity=parity,
                cycles=permutation_cycles(permutation),
                unrestricted_three_cycles=(
                    None if parity else minimum_unrestricted_three_cycles(permutation)
                ),
            )
        )
    return ResidualReport(corner_parity, tuple(reports))


def _bits_to_mask(bits: Sequence[int]) -> int:
    mask = 0
    for index, bit in enumerate(bits):
        if bit not in (0, 1):
            raise ValueError("parity vectors must contain only zeroes and ones")
        mask |= bit << index
    return mask


def parity_repair_path(
    current_parity: Sequence[int],
    decomposition: Cube666Decomposition,
    required_parity: int = 0,
) -> tuple[str, ...]:
    """Find a shortest inner-move path to the requested cluster parity.

    The search has at most 2**6 states.  Move effects with the same six-bit column
    are deduplicated, so the result is deterministic and optimal in primitive
    inner-slice quarter turns.  In the classical pipeline the corners are solved
    first and ``required_parity`` remains zero.  The optional argument is kept for
    diagnostics of other target parity classes.
    """

    width = len(decomposition.physical_clusters)
    if len(current_parity) != width:
        raise ValueError(f"expected parity vector length {width}, got {len(current_parity)}")
    if required_parity not in (0, 1):
        raise ValueError("required_parity must be zero or one")
    defect = tuple(parity ^ required_parity for parity in current_parity)
    start = _bits_to_mask(defect)
    if start == 0:
        return ()

    representative_by_effect: dict[int, str] = {}
    for name, vector in decomposition.parity_effects:
        effect = _bits_to_mask(vector)
        if effect:
            old = representative_by_effect.get(effect)
            if old is None or name < old:
                representative_by_effect[effect] = name
    moves = tuple(sorted((name, effect) for effect, name in representative_by_effect.items()))

    queue = deque((start,))
    previous: dict[int, tuple[int, str] | None] = {start: None}
    while queue:
        mask = queue.popleft()
        for name, effect in moves:
            next_mask = mask ^ effect
            if next_mask in previous:
                continue
            previous[next_mask] = (mask, name)
            if next_mask == 0:
                path: list[str] = []
                cursor = 0
                while cursor != start:
                    parent, move_name = previous[cursor]  # type: ignore[misc]
                    path.append(move_name)
                    cursor = parent
                path.reverse()
                return tuple(path)
            queue.append(next_mask)
    raise ValueError(
        f"parity defect {defect} (current={tuple(current_parity)}, required={required_parity}) "
        "is unreachable by inner moves"
    )


def apply_path(
    state: Sequence[int],
    generators: Mapping[str, Sequence[int]],
    path: Iterable[str],
) -> tuple[int, ...]:
    """Apply a named path using the competition's pullback convention."""

    current = tuple(state)
    for name in path:
        permutation = generators[name]
        if len(permutation) != len(current):
            raise ValueError(f"generator {name!r} has the wrong length")
        current = tuple(current[index] for index in permutation)
    return current
