"""Train the Phase-2 V model for the two-phase (Kociemba-style) solver.

Phase 2 solves WITHIN the subgroup H generated by the 6 TOP faces. We build a
restricted Megaminx exposing only those 12 generators, so the shared training loop
draws restricted random walks from solved automatically. The model is a plain
ResMLPDistance (no masking) trained to predict walk depth, with exact solved/d1
anchors mixed into every epoch so V(solved) stays calibrated.

    .venv/Scripts/python.exe megaminx/scripts/110_train_phase2.py \
        --config megaminx/configs/m_phase2_pretrain.yaml \
        --output megaminx/models/m_phase2_v0

See megaminx/two_phase_plan.md for the full recipe and validation gates.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch
import yaml

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT / "src"))
sys.path.insert(0, str(PROJECT.parent / "src"))

from cayley.model import ResMLPDistance
from cayley.training import TrainConfig, train
from megaminx.puzzle import Megaminx
from megaminx.two_phase import build_phase2_puzzle, phase2_move_names, phase2_v0_d1_anchors


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path, help="directory for checkpoints")
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    ap.add_argument("--epochs", type=int, default=None, help="override config n_epochs")
    args = ap.parse_args()

    with open(args.config, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    model_cfg = cfg["model"]
    train_cfg_dict = cfg["training"]
    anchor_cfg = cfg.get("anchors", {})
    if args.epochs is not None:
        train_cfg_dict["n_epochs"] = args.epochs
    train_cfg_dict["device"] = args.device
    train_cfg_dict["seed"] = cfg.get("seed", 0)

    full = Megaminx.load(PROJECT / "data" / "puzzle_info.json")
    puzzle = build_phase2_puzzle(full)

    model = ResMLPDistance(
        state_size=model_cfg["state_size"],
        num_classes=model_cfg["num_classes"],
        hidden_dims=tuple(model_cfg["hidden_dims"]),
        num_res_blocks=model_cfg["num_res_blocks"],
        encoding=model_cfg.get("encoding", "embedding"),
        embed_dim=model_cfg.get("embed_dim", 16),
    )
    print(f"PHASE 2 (restricted subgroup H) -- {len(puzzle.move_names)} generators: "
          f"{phase2_move_names(full)}", flush=True)
    print(f"model params: {model.num_parameters():,}", flush=True)
    print(f"device: {args.device}", flush=True)
    print(f"training: {train_cfg_dict}", flush=True)
    print(f"anchors: {anchor_cfg}", flush=True)

    tc = TrainConfig(**train_cfg_dict)

    n_v0 = int(anchor_cfg.get("n_v0", 0))
    n_d1 = int(anchor_cfg.get("n_d1_per_move", 0))
    anchor_sampler = None
    if n_v0 > 0 or n_d1 > 0:
        a_states, a_depths = phase2_v0_d1_anchors(puzzle, n_v0, n_d1, args.device)
        print(f"anchor batch: {a_states.shape[0]:,} states "
              f"(V0={n_v0:,}, d1={len(puzzle.move_names)}x{n_d1:,})", flush=True)

        def anchor_sampler(_seed):
            return a_states, a_depths

    def log(stats):
        print(f"epoch {stats.epoch:4d} | loss {stats.loss:.4f} | lr {stats.lr:.2e} | "
              f"{stats.elapsed_s:.1f}s", flush=True)

    result = train(model, puzzle, tc, checkpoint_dir=args.output, on_epoch_end=log,
                   anchor_sampler=anchor_sampler)
    print(f"final loss: {result.final_loss:.4f}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
